name: Cache Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache demo directory
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-f5f3244

      - name: prime-cache-f5f3244
        run: echo "Cache status"
